<a href="https://colab.research.google.com/github/Bipanaale/Machine_learning/blob/main/num_py_day_1%2B_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("hello")

hello


same values but python list and numpy array execute different values

In [3]:
import numpy as np

py_list = [1, 2, 3]
np_array = np.array([1, 2, 3])

print(py_list * 2)
print(np_array * 2)
//samevaluesbutpythonlistandnumpyarra

[1, 2, 3, 1, 2, 3]
[2 4 6]


num py array is faster in execution



In [10]:
import time
list1 = list(range(1000000))
sum = 0
#using python list
start_time = time.time()
for num in list1:
  sum += num
end_time = time.time()

print(f"sum of list1:{sum}")
print(f"time taken on python list: {end_time-start_time}")



sum of list1:499999500000
time taken on python list: 0.14052271842956543


In [11]:
#in num py array

start_time = time.time()
sum = np.sum(np_array)
end_time = time.time()

print(f"Sum of np_array: {sum}")
print(f"Time taken on numpy array: {end_time-start_time}")


Sum of np_array: 6
Time taken on numpy array: 0.00017404556274414062


In [13]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [15]:
x = [1,2,3]
a = np.array(x)
print(a)

[1 2 3]


In [18]:
x = np.zeros(4)
print(x)


[0. 0. 0. 0.]


In [22]:
x = input()
print(type(x))



<class 'str'>


In [24]:
np.zeros((3,4), dtype=np.int32)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int32)

In [26]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [30]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
r = range(1, 10)
print(r)  # range object ho r chai

range(1, 10)


In [35]:
np.linspace(2, 10, 5)

array([ 2.,  4.,  6.,  8., 10.])

In [37]:
np.logspace(0, 3, num=4, base=10)

array([   1.,   10.,  100., 1000.])

In [39]:
np.full((5,2), fill_value=2, dtype=np.int32)


array([[2, 2],
       [2, 2],
       [2, 2],
       [2, 2],
       [2, 2]], dtype=int32)

In [41]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [43]:
a = np.array([[1, 2, 3],
              [4, 5, 6]], dtype=np.int64)
print(a)

[[1 2 3]
 [4 5 6]]


In [45]:
print(f"Data type (dtype):       {a.dtype}")
print(f"Shape (rows, cols):     {a.shape}")
print(f"Total elements (size):  {a.size}")
print(f"Number of dimensions:   {a.ndim}")
print(f"Bytes per item:         {a.itemsize} bytes")
print(f"Total memory (nbytes):  {a.nbytes} bytes")

Data type (dtype):       int64
Shape (rows, cols):     (2, 3)
Total elements (size):  6
Number of dimensions:   2
Bytes per item:         8 bytes
Total memory (nbytes):  48 bytes


In [47]:
arr1 = np.array([.2, .3, 4.8, .4, 77, 9.1])
print(arr1)
print(arr1.dtype)

[ 0.2  0.3  4.8  0.4 77.   9.1]
float64


In [49]:
arr2 = np.array([.2, .3, 4.8, .4, 77, 9.1], dtype=np.int64)
print(arr2)
print(arr2.dtype)

[ 0  0  4  0 77  9]
int64


In [51]:
arr = np.array([1, 2, 3])
print(arr.astype(np.float64))

[1. 2. 3.]


In [53]:
arr = np.arange(16)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [55]:
arr.shape

(16,)

In [57]:

arr.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [60]:
#array dimensions with indexing
x = np.array([1,2,3,4,5])
print(x)

[1 2 3 4 5]


In [62]:
print(x[0])
print(x[3])
print(x[-1])

1
4
5


In [64]:
class_marks = np.array(
          [[40, 50, 60],
          [70, 80, 90],
          [55, 65, 75]])

print(class_marks)

[[40 50 60]
 [70 80 90]
 [55 65 75]]


In [66]:
print(class_marks[0][0])
print(class_marks[1][2])
print(class_marks[2][1])

40
90
65


In [70]:
school_marks = np.array(
              [[[40, 50],
                [60, 70],
                [50, 60]],

                 [[80, 85],
                  [90, 95],
                   [90, 100]]])

print(school_marks)

[[[ 40  50]
  [ 60  70]
  [ 50  60]]

 [[ 80  85]
  [ 90  95]
  [ 90 100]]]


In [72]:
school_marks.shape


(2, 3, 2)

In [74]:
print(school_marks[0][0][1])
print(school_marks[1][1][0])


50
90


In [77]:
print(school_marks[1, 2, 1])

100


In [78]:
import random


In [83]:
np.random.seed(1337)
np.random.randint(1,10)

8

In [86]:
np.random.randint(1, 5)

1

In [88]:
np.random.randint(0, 100, size=5)

array([84, 72,  9,  6, 54])

In [90]:
np.random.randint(10, 50, size=(2,3))

array([[16, 32, 12],
       [21, 11, 33]])

In [92]:
np.random.rand()

0.005342560717922162

In [94]:
np.random.rand(5)

array([0.8635716 , 0.40502088, 0.44050168, 0.14085409, 0.82018089])

In [96]:
np.random.rand(2, 3)

array([[0.69225514, 0.69298743, 0.83769031],
       [0.61673252, 0.66509648, 0.45771258]])

In [98]:
np.random.random((2, 3))


array([[0.96035115, 0.05294031, 0.52608945],
       [0.67816269, 0.74905771, 0.5389452 ]])

In [100]:
arr = np.array([1,2,3,4,5])
print(arr)
np.random.shuffle(arr)
print(arr)

[1 2 3 4 5]
[2 3 1 4 5]


In [102]:
import numpy as np
import ipywidgets as widgets
from ipywidgets import interact

@interact(rows=(1,10), cols=(1,10))
def create_array(rows=3, cols=3):
    return np.random.randint(0, 100, size=(rows, cols))

interactive(children=(IntSlider(value=3, description='rows', max=10, min=1), IntSlider(value=3, description='c…

In [108]:

# Decorators: enhance the base function
import time

def timer(base_fn):
  def enhanced_fn():
    start_time = time.time()
    base_fn()
    stop_time = time.time()
    print(f"Time taken: {stop_time - start_time} seconds")
  return enhanced_fn

@timer
def brewtea():
  print("Making Tea")
  time.sleep(1)
  print("Tea is ready")

brewtea()


Making Tea
Tea is ready
Time taken: 1.0003364086151123 seconds


assignment num py day 1
assignment 1 1. Array Creation Practice
Create the following arrays using different NumPy functions:

A 1D array with values from 10 to 50 with a step of 5 using np.arange()
A 3x3 identity matrix using np.eye()
A 4x5 array filled with the value 7 using np.full()
A 1D array with 8 evenly spaced values between 0 and 100 using np.linspace()


In [109]:
import numpy as np



In [112]:
arr1 = np.arange(10,51,5)
print("1D array using arrange:",arr1)

1D array using arrange: [10 15 20 25 30 35 40 45 50]


In [121]:
arr2 = np.eye(3,3)
print(arr2)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [124]:
arr3 = np.full((4, 5), 7)
print( arr3)


[[7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]]


In [126]:
arr4 = np.linspace(0, 100, 8)
print( arr4)

[  0.          14.28571429  28.57142857  42.85714286  57.14285714
  71.42857143  85.71428571 100.        ]


In [129]:
!git checkout  -b Main

fatal: not a git repository (or any of the parent directories): .git
